#!/bin/sh -x
compile_all=0
FC=mpif90
INCS="-I. -I../FV3/gfsphysics/ -I../FMS/include -I../FV3/atmos_cubed_sphere -I../FMS/fv3gfs"
FLAGS64=" -traceback -real-size 64 -DSTOCHY_UNIT_TEST -c "$INCS
FLAGS=" -traceback -DSTOCHY_UNIT_TEST -c "$INCS
if [ $compile_all -eq 1 ];then
   rm -f *.i90 *.i *.o *.mod lib*a
   $FC ${FLAGS}   fv_control_stub.F90
   $FC ${FLAGS}   atmosphere_stub.F90
   $FC ${FLAGS64} stochy_namelist_def.F90
   $FC ${FLAGS64} stochy_resol_def.f
   $FC ${FLAGS64} stochy_gg_def.f
   $FC ${FLAGS64} spectral_layout.F90
   $FC ${FLAGS64} stochy_layout_lag.f
   $FC ${FLAGS64} pln2eo_stochy.f
   $FC ${FLAGS64} setlats_a_stochy.f
   $FC ${FLAGS64} setlats_lag_stochy.f
   $FC ${FLAGS64} glats_stochy.f
   $FC ${FLAGS64} gozrineo_stochy.f
   $FC ${FLAGS64} dezouv_stochy.f
   $FC ${FLAGS64} dozeuv_stochy.f
   $FC ${FLAGS64} epslon_stochy.f
   $FC ${FLAGS64} four_to_grid_stochy.f
   $FC ${FLAGS64} sumfln_stochy.f
   $FC ${FLAGS64} get_lats_node_a_stochy.f
   $FC ${FLAGS64} get_ls_node_stochy.f
   $FC ${FLAGS64} compns_stochy.F90
   $FC ${FLAGS64} stochy_internal_state_mod.F90
   $FC ${FLAGS64} getcon_lag_stochy.f
   $FC ${FLAGS64} getcon_spectral.F90
   $FC ${FLAGS64} initialize_spectral_mod.F90
   $FC ${FLAGS64} standalone_stochy_module.F90
   $FC ${FLAGS64} stochy_patterngenerator.F90
   $FC ${FLAGS64} stochy_data_mod.F90
   $FC ${FLAGS64} get_stochy_pattern.F90
   $FC ${FLAGS64} stochastic_physics.F90
   ar rv libstochastic_physics.a *.o
fi
$FC -traceback -real-size 64 -qopenmp -o standalone_stochy standalone_stochy.F90 ${INCS} -I/apps/netcdf/4.7.0/intel/18.0.5.274/include -L. -lstochastic_physics -L../FV3/atmos_cubed_sphere -lfv3core -L../FMS/FMS_INSTALL -lfms -L../FV3/gfsphysics -lgfsphys -L/scratch2/NCEPDEV/nwprod/NCEPLIBS/compilers/intel/18.0.5.274/lib -lsp_v2.0.3_d -L/scratch1/NCEPDEV/nems/emc.nemspara/soft/esmf/8.0.0bs48-intel18.0.5.274-impi2018.0.4-netcdf4.6.1/lib -Wl,-rpath,/scratch1/NCEPDEV/nems/emc.nemspara/soft/esmf/8.0.0bs48-intel18.0.5.274-impi2018.0.4-netcdf4.6.1/lib -lesmf -L/apps/netcdf/4.7.0/intel/18.0.5.274/lib -lnetcdff -lnetcdf
